spring.datasource.url=jdbc:postgresql://localhost:5432/connective_database
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraciones adicionales recomendadas para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8081

# JWT
app.jwt.secret=9l9biE43iBpHSA7S9tDZnTLtB3cirPlI
app.jwt.expiration-ms=3000000

# Flyway
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.springframework.web=DEBUG
#spring.flyway.baseline-on-migrate=true

# Opcional: tunables
chat.maxHistory=30